[package]
name = "standalone"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "standalone"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
splug = { path = "../plugin" }

# CLI argument parsing
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
