[package]
name = "debug-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
tonic = "0.12"
prost = "0.13"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
crossbeam-channel = "0.5"
anyhow = "1.0"
tracing = "0.1"
pal = { path = "../pal" }

[build-dependencies]
tonic-build = "0.12"

[dev-dependencies]
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
